#include "led.h"

void Led_Init(LedHandle_t *handle)
{
    // Usually the pin is configured in MX_GPIO_Init generated by CubeMX.
    // Additional initialization can be added here if needed.
    (void)handle;
}

void Led_On(LedHandle_t *handle)
{
    HAL_GPIO_WritePin(handle->Port, handle->Pin, GPIO_PIN_SET);
}

void Led_Off(LedHandle_t *handle)
{
    HAL_GPIO_WritePin(handle->Port, handle->Pin, GPIO_PIN_RESET);
}

void Led_Toggle(LedHandle_t *handle)
{
    HAL_GPIO_TogglePin(handle->Port, handle->Pin);
}
